from __future__ import annotations

from pathlib import Path

from nocturne import gitwork, opencode_driver, verifier
from nocturne._logging import get_logger
from nocturne.config import Config
from nocturne.guardrails import GuardrailViolation, WorktreeContext, check_repo_allowed
from nocturne.gitwork import branch_name, commit_push, make_worktree, open_pr
from nocturne.models import OpenCodeResult, Task


class OrchestratorError(Exception):
    pass


def format_error(result: OpenCodeResult) -> str:
    lines: list[str] = [f"exit_code={result.exit_code}"]
    if result.error_events:
        lines.append(f"error_events_count={len(result.error_events)}")
        first = result.error_events[0]
        message = first.get("message") if isinstance(first, dict) else None
        if message is None and isinstance(first, dict):
            message = first.get("type")
        lines.append(f"first_error={message!r}")
    else:
        lines.append("error_events_count=0")
    lines.append(f"sentinel_seen={result.sentinel_seen}")
    if result.need_input_question:
        lines.append(f"need_input_question={result.need_input_question!r}")
    return "\n".join(lines)


def _worktree_path_for(task: Task, cfg: Config) -> Path:
    safe_slug = task.repo_slug.replace("/", "__")
    name = f"{safe_slug}-issue-{task.issue_number}-{task.attempts}"
    return Path(cfg.opencode.worktree_root) / name


def process_task(task: Task, cfg: Config, store, *, dry_run: bool = False) -> Task:
    log = get_logger("nocturne.orchestrator")

    # Guardrail: repo allowlist (propagates GuardrailViolation before any side effect).
    _repo_cfg = check_repo_allowed(task.repo_slug, cfg)

    # Bump attempts once for this task invocation (single worktree per process_task call).
    store.increment_attempts(task.id)
    task.attempts += 1
    store.update_status(task.id, "running")
    task.status = "running"

    task.branch = branch_name(task.issue_number, task.attempts)
    worktree_path = _worktree_path_for(task, cfg)
    wt = make_worktree(Path(task.checkout_path), task.branch, task.base, worktree_path)

    success = False
    pid_callback = lambda pid: store.update_pid(task.id, pid)  # noqa: E731
    last_fail: str | None = None
    result: OpenCodeResult | None = None

    try:
        with WorktreeContext(wt, expected_base=task.base):
            for attempt in range(cfg.guardrails.max_attempts):
                log.info(
                    "orchestrator attempt %s/%s task=%s",
                    attempt + 1,
                    cfg.guardrails.max_attempts,
                    task.id,
                )
                result = opencode_driver.run(
                    task,
                    wt,
                    cfg,
                    prior_failure=last_fail,
                    on_pid_started=pid_callback,
                )

                if result.sentinel_seen:
                    log.warning(
                        "sentinel detected on task=%s question=%r",
                        task.id,
                        result.need_input_question,
                    )
                    last_fail = f"need-input requested: {result.need_input_question}"
                    # M1: park-not-yet-implemented; break and mark failed below.
                    break

                if result.exit_code != 0 or result.error_events:
                    last_fail = format_error(result)
                    log.warning(
                        "opencode failed on task=%s exit=%s errors=%s",
                        task.id,
                        result.exit_code,
                        len(result.error_events),
                    )
                    continue

                v = verifier.verify(task, wt)
                if not v.passed:
                    parts: list[str] = [v.stdout or "", "---STDERR---", v.stderr or ""]
                    fail_text = "\n".join(parts)
                    if v.reason:
                        fail_text += f"\n[reason: {v.reason}]"
                    last_fail = fail_text
                    log.warning(
                        "verify failed on task=%s exit=%s reason=%s",
                        task.id,
                        v.exit_code,
                        v.reason,
                    )
                    continue

                # Success path.
                if not dry_run:
                    commit_push(wt, f"closes #{task.issue_number}: {task.title}")
                    pr_url = open_pr(
                        task.repo_slug,
                        task.branch,
                        task.base,
                        task.title,
                        f"Closes #{task.issue_number}\n\nGenerated by Nocturne.",
                    )
                else:
                    pr_url = "dry-run"

                task.pr_url = pr_url
                store.update_pr_url(task.id, pr_url)
                store.update_status(task.id, "done")
                task.status = "done"
                success = True
                log.info("task=%s done pr_url=%s", task.id, pr_url)
                break
            else:
                # Loop exhausted without success.
                store.update_status(task.id, "failed")
                task.status = "failed"
                log.warning("task=%s exhausted attempts; marking failed", task.id)

        # If we broke out via sentinel, the for/else didn't run — set failed here.
        if not success and task.status != "failed":
            store.update_status(task.id, "failed")
            task.status = "failed"
    finally:
        if success:
            gitwork.cleanup(wt, Path(task.checkout_path))
        # else: retain worktree for debugging (default behavior).

    return task
