from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from nocturne import gitwork, opencode_driver, verifier
from nocturne._gh_retry import GhError, IssueNotFound
from nocturne._logging import get_logger
from nocturne.config import Config, RepoConfig
from nocturne.gitwork import branch_name, commit_push, make_worktree, open_pr
from nocturne.guardrails import (
    GuardrailViolation,
    WorktreeContext,
    check_repo_allowed,
    check_wallclock,
)
from nocturne.models import OpenCodeResult, ParkedTask, PRWatch, RunReport, Task, TriageResult
from nocturne.sources.github_issues import (
    fetch_eligible,
    find_blocking_open_pr,
    get_issue_snapshot,
)
from nocturne.sources.github_pr import parse_pr_number
from nocturne.store import Store
from nocturne.triage import triage_batch


class OrchestratorError(Exception):
    pass


def format_error(result: OpenCodeResult) -> str:
    lines: list[str] = [f"exit_code={result.exit_code}"]
    if result.error_events:
        lines.append(f"error_events_count={len(result.error_events)}")
        first = result.error_events[0]
        message = first.get("message") if isinstance(first, dict) else None
        if message is None and isinstance(first, dict):
            message = first.get("type")
        lines.append(f"first_error={message!r}")
    else:
        lines.append("error_events_count=0")
    lines.append(f"sentinel_seen={result.sentinel_seen}")
    if result.need_input_question:
        lines.append(f"need_input_question={result.need_input_question!r}")
    return "\n".join(lines)


def _worktree_path_for(task: Task, cfg: Config) -> Path:
    safe_slug = task.repo_slug.replace("/", "__")
    name = f"{safe_slug}-issue-{task.issue_number}-{task.attempts}"
    return Path(cfg.opencode.worktree_root) / name


_PR_BODY_FILENAME = ".nocturne-pr-body.md"


def _read_pr_body(worktree: Path, task: Task) -> tuple[str, str]:
    """Read the PR title + body opencode wrote per task.md.jinja2 Step 6.

    Contract: first '# <line>' is the PR title (and commit message subject).
    Everything below is the GitHub PR body. If the file is missing or has
    no H1, fall back to the legacy title + 'Closes #N\\n\\nGenerated by Nocturne.'.
    """
    fallback_title = f"closes #{task.issue_number}: {task.title}"
    fallback_body = f"Closes #{task.issue_number}\n\nGenerated by Nocturne."

    pr_body_path = worktree / _PR_BODY_FILENAME
    if not pr_body_path.is_file():
        return fallback_title, fallback_body

    content = pr_body_path.read_text(encoding="utf-8").strip()
    if not content:
        return fallback_title, fallback_body

    lines = content.split("\n")
    title: str | None = None
    body_start = 0
    for i, raw in enumerate(lines):
        stripped = raw.strip()
        if stripped.startswith("# "):
            title = stripped[2:].strip()
            body_start = i + 1
            break

    if title is None:
        return fallback_title, content

    body_lines = lines[body_start:]
    while body_lines and not body_lines[0].strip():
        body_lines.pop(0)
    body = "\n".join(body_lines).strip()
    if not body:
        body = f"Closes #{task.issue_number}"
    return title, body


def _check_issue_drift(task: Task, repo_cfg: RepoConfig) -> str | None:
    """Re-fetch live issue state immediately before PR creation and return a
    human-readable reason to abort, or None to proceed.

    Catches the three things a maintainer can do to an issue while opencode is
    running for many minutes: close it, pull the trigger label (signalling "I'm
    handling this"), or open a PR that already resolves it. On a transient gh
    failure we return None (proceed) - open_pr is the final backstop, and a
    network blip must not strand otherwise-finished work.
    """
    log = get_logger("nocturne.orchestrator")
    try:
        snapshot = get_issue_snapshot(task.repo_slug, task.issue_number)
    except IssueNotFound:
        return "issue not found (deleted or transferred)"
    except GhError as e:
        log.warning("task=%s issue-state recheck failed (proceeding): %s", task.id, e)
        return None

    if snapshot.state == "CLOSED":
        return "issue closed during execution"
    if repo_cfg.label and repo_cfg.label not in snapshot.labels:
        return f"trigger label {repo_cfg.label!r} removed during execution"

    try:
        blocking_pr = find_blocking_open_pr(task.repo_slug, task.issue_number)
    except GhError as e:
        log.warning("task=%s linked-PR recheck failed (proceeding): %s", task.id, e)
        blocking_pr = None
    if blocking_pr is not None:
        return f"open PR #{blocking_pr} already addresses this issue"

    return None


def _provider_key_envs(cfg: Config) -> set[str]:
    """Provider API key env-var names to strip from the verify subprocess
    (it runs agent-authored test code and needs no model access)."""
    names = {p.api_key_env for p in cfg.providers.values()}
    names.add("OPENCODE_PROVIDER_API_KEY")
    return names


def _register_pr_watch(task: Task, pr_url: str, store: Store) -> None:
    now = datetime.now(timezone.utc)
    store.add_pr_watch(
        PRWatch(
            pr_url=pr_url,
            task_id=task.id,
            repo_slug=task.repo_slug,
            pr_number=parse_pr_number(pr_url),
            branch=task.branch,
            base=task.base,
            created_at=now,
            updated_at=now,
        )
    )


def process_pr_reaction(
    watch: PRWatch, kind: str, feedback: str, cfg: Config, store: Store
) -> tuple[bool, int]:
    """Re-dispatch the agent onto an open PR's branch to fix CI or address
    review comments. Returns (pushed_a_fix, tokens_used). Opens NO new PR;
    pushes a fast-forward commit onto the existing branch.
    """
    from nocturne.prompts.render import render_pr_fix_prompt

    log = get_logger("nocturne.orchestrator")
    task = store.get_task(watch.task_id)
    if task is None:
        log.warning("pr-reaction: task %s missing for PR %s", watch.task_id, watch.pr_url)
        return (False, 0)

    # Fixes need not add a new test (we're addressing feedback, not adding scope).
    task = task.model_copy(update={"branch": watch.branch, "require_new_test": False})

    safe_slug = task.repo_slug.replace("/", "__")
    wt_path = Path(cfg.opencode.worktree_root) / f"{safe_slug}-pr-{watch.pr_number}-fix-{watch.fix_attempts}"
    wt = gitwork.make_worktree_from_branch(Path(task.checkout_path), watch.branch, wt_path)

    tokens = 0
    try:
        with WorktreeContext(wt, expected_base=task.base):
            prompt = render_pr_fix_prompt(
                task, pr_number=watch.pr_number, kind=kind, feedback=feedback, cfg=cfg
            )
            result = opencode_driver.run(
                task, wt, cfg,
                on_pid_started=lambda pid: store.update_pid(task.id, pid),
                prompt_override=prompt,
            )
            tokens = result.token_usage
            if tokens:
                store.add_task_tokens(task.id, tokens)
            if result.sentinel_seen or result.exit_code != 0 or result.error_events:
                log.warning("pr-reaction: opencode did not produce a clean fix for %s", watch.pr_url)
                return (False, tokens)

            v = verifier.verify(task, wt, strip_env=_provider_key_envs(cfg))
            if not v.passed:
                log.warning("pr-reaction: verify failed for %s (%s)", watch.pr_url, v.reason)
                return (False, tokens)

            try:
                gitwork.commit_push_followup(wt, f"Address {kind} feedback on #{watch.pr_number}")
            except (GuardrailViolation, gitwork.GitworkError) as e:
                log.warning("pr-reaction: could not push fix for %s: %s", watch.pr_url, e)
                return (False, tokens)
            log.info("pr-reaction: pushed %s fix for %s", kind, watch.pr_url)
            return (True, tokens)
    finally:
        # Always tear down the ephemeral fix worktree - even on failure. A
        # leaked worktree keeps the PR branch checked out and blocks every
        # subsequent fix attempt for that branch. The branch's state lives on
        # the PR, so there is nothing to inspect locally.
        gitwork.cleanup(wt, Path(task.checkout_path))


def process_task(task: Task, cfg: Config, store, *, dry_run: bool = False) -> Task:
    log = get_logger("nocturne.orchestrator")

    _repo_cfg = check_repo_allowed(task.repo_slug, cfg)

    if store.get_task(task.id) is None:
        store.insert_task(task)

    store.increment_attempts(task.id)
    task.attempts += 1
    store.update_status(task.id, "running")
    task.status = "running"

    task.branch = branch_name(task.issue_number, task.attempts)
    worktree_path = _worktree_path_for(task, cfg)
    # Reap old failed/aborted worktrees so they cannot exhaust disk over time.
    reaped = gitwork.reap_stale_worktrees(
        worktree_path.parent, cfg.opencode.worktree_ttl_hours
    )
    if reaped:
        log.info("reaped %s stale worktree(s) under %s", reaped, worktree_path.parent)
    wt = make_worktree(Path(task.checkout_path), task.branch, task.base, worktree_path)

    success = False
    pid_callback = lambda pid: store.update_pid(task.id, pid)  # noqa: E731
    last_fail: str | None = None
    result: OpenCodeResult | None = None

    # Provider API keys to strip from the verify subprocess: it runs
    # agent-authored test code and needs no model access.
    verify_strip_env = _provider_key_envs(cfg)

    try:
        with WorktreeContext(wt, expected_base=task.base):
            for attempt in range(cfg.guardrails.max_attempts):
                log.info(
                    "orchestrator attempt %s/%s task=%s",
                    attempt + 1,
                    cfg.guardrails.max_attempts,
                    task.id,
                )
                result = opencode_driver.run(
                    task,
                    wt,
                    cfg,
                    prior_failure=last_fail,
                    on_pid_started=pid_callback,
                )

                if result.token_usage:
                    store.add_task_tokens(task.id, result.token_usage)
                    task.token_usage += result.token_usage

                # Mid-run budget guard: stop retrying a single task once its
                # cumulative token spend reaches the global budget, so one task
                # cannot blow far past it across attempts.
                if task.token_usage >= cfg.guardrails.token_budget:
                    last_fail = (
                        f"token budget exhausted "
                        f"({task.token_usage} >= {cfg.guardrails.token_budget})"
                    )
                    log.warning("task=%s %s; stopping retries", task.id, last_fail)
                    break

                if result.sentinel_seen:
                    log.warning(
                        "sentinel detected on task=%s question=%r",
                        task.id,
                        result.need_input_question,
                    )
                    last_fail = f"need-input requested: {result.need_input_question}"
                    # M1: park-not-yet-implemented; break and mark failed below.
                    break

                if result.exit_code != 0 or result.error_events:
                    last_fail = format_error(result)
                    log.warning(
                        "opencode failed on task=%s exit=%s errors=%s",
                        task.id,
                        result.exit_code,
                        len(result.error_events),
                    )
                    continue

                v = verifier.verify(task, wt, strip_env=verify_strip_env)
                if not v.passed:
                    parts: list[str] = [v.stdout or "", "---STDERR---", v.stderr or ""]
                    fail_text = "\n".join(parts)
                    if v.reason:
                        fail_text += f"\n[reason: {v.reason}]"
                    last_fail = fail_text
                    log.warning(
                        "verify failed on task=%s exit=%s reason=%s",
                        task.id,
                        v.exit_code,
                        v.reason,
                    )
                    continue

                # Pre-PR drift guard: re-fetch live issue state between opencode
                # exit and PR creation so we never race a maintainer who closed
                # the issue, pulled the trigger label, or already opened a PR for
                # it while opencode was running (potentially many minutes).
                drift_reason = _check_issue_drift(task, _repo_cfg)
                if drift_reason is not None:
                    store.update_status(task.id, "aborted")
                    task.status = "aborted"
                    log.info(
                        "task=%s aborting without PR (issue #%s): %s",
                        task.id, task.issue_number, drift_reason,
                    )
                    success = True  # graceful exit; finally cleanup still runs
                    break

                # Success path.
                if not dry_run:
                    pr_title, pr_body = _read_pr_body(wt, task)
                    try:
                        commit_push(wt, pr_title, task.base)
                    except GuardrailViolation as e:
                        last_fail = f"guardrail blocked commit: {e}"
                        log.warning("task=%s commit blocked by guardrail: %s", task.id, e)
                        continue  # retry with feedback; never push the blocked diff
                    pr_url = open_pr(
                        task.repo_slug,
                        task.branch,
                        task.base,
                        pr_title,
                        pr_body,
                    )
                else:
                    pr_url = "dry-run"

                task.pr_url = pr_url
                store.update_pr_url(task.id, pr_url)
                store.update_status(task.id, "done")
                task.status = "done"
                success = True
                log.info("task=%s done pr_url=%s", task.id, pr_url)

                # Register the PR for the post-PR feedback loop (CI fixes,
                # review-comment handling). Best-effort: never fail the task.
                if not dry_run and cfg.reactions.enabled:
                    try:
                        _register_pr_watch(task, pr_url, store)
                    except Exception as e:
                        log.warning("could not register PR watch for %s: %s", task.id, e)

                if not dry_run:
                    try:
                        run_id = store.start_review_run(task.id, pr_url)
                        store.end_review_run(run_id, attempts=1, clean=True)
                    except Exception as e:
                        log.warning(
                            "could not record review_run for %s (non-blocking): %s",
                            task.id, e,
                        )
                break
            else:
                # Loop exhausted without success.
                store.update_status(task.id, "failed")
                task.status = "failed"
                log.warning("task=%s exhausted attempts; marking failed", task.id)

        # If we broke out via sentinel, the for/else didn't run - set failed here.
        if not success and task.status != "failed":
            store.update_status(task.id, "failed")
            task.status = "failed"
    finally:
        if success and not dry_run:
            gitwork.cleanup(wt, Path(task.checkout_path))

    return task


def partition_eligible(
    issues: list[Task], store: Store,
) -> tuple[list[Task], list[Task]]:
    """Partition fetched issues against existing store state.

    Returns (to_triage, resumed) where:
      - to_triage: fresh tasks not yet in store; go to triage_batch
      - resumed:   tasks in store with status='selected' AND non-empty answer
                   (i.e. user resumed them via `nocturne resume`); bypass triage
                   and go directly to process_task with the stored row
      - Everything else (done, aborted, parked, skipped, running, failed,
        selected-without-answer) is silently dropped - already handled this
        lifecycle. An INFO log records the skip per task.

    Shared between orchestrator.run_batch (CLI run-once path) and
    daemon.run_one_cycle (long-running daemon poll). Centralising this is
    why bug class 'daemon reprocesses already-done tasks' (M5 Test 3
    regression) doesn't return.
    """
    log = get_logger("nocturne.orchestrator")
    to_triage: list[Task] = []
    resumed: list[Task] = []
    for task in issues:
        existing = store.get_task(task.id)
        if existing is None:
            to_triage.append(task)
            continue
        if existing.status == "selected" and (existing.answer or "").strip():
            resumed.append(existing)
            continue
        log.info(
            "task %s already in store (status=%s); skipping in this batch",
            task.id, existing.status,
        )
    return to_triage, resumed


def _dispatch_triaged(
    task: Task,
    tr: TriageResult,
    cfg: Config,
    store: Store,
    *,
    dry_run: bool = False,
) -> str:
    """Dispatch a triaged task to the right pipeline.

    Returns one of: 'done', 'failed', 'parked', 'skipped'.
    SKIP and NEED_INPUT MUST NOT invoke process_task (plan invariant).
    """
    if tr.outcome == "SKIP":
        return "skipped"
    if tr.outcome == "NEED_INPUT":
        from nocturne.askflow import park_task, post_park_comment

        store.insert_task(task)
        question = tr.reason or "Triage flagged this issue as ambiguous; please clarify."
        park_task(task, question, store)
        if not dry_run:
            try:
                post_park_comment(task.repo_slug, task.issue_number, question)
            except Exception as exc:  # noqa: BLE001 - batch must keep going
                log = get_logger("nocturne.orchestrator")
                log.warning(
                    "post_park_comment unexpectedly raised on %s#%s (swallowed): %s",
                    task.repo_slug, task.issue_number, exc,
                )
        else:
            log = get_logger("nocturne.orchestrator")
            log.info(
                "dry-run: would have posted question comment on %s#%s",
                task.repo_slug, task.issue_number,
            )
        return "parked"
    store.insert_task(task)
    result_task = process_task(task, cfg, store, dry_run=dry_run)
    return result_task.status


def run_batch(
    repo_cfg: RepoConfig,
    cfg: Config,
    store: Store,
    *,
    dry_run: bool = False,
) -> RunReport:
    """Fetch eligible issues, triage, and process each per outcome.

    Returns an aggregate RunReport. Never raises on individual task failures -
    all errors are collected into `RunReport.errors`. Wallclock guard is
    checked between tasks; a violation aborts the remainder of the batch.
    """
    log = get_logger("nocturne.orchestrator")
    started_at = datetime.now(timezone.utc)
    done: list[Task] = []
    parked: list[ParkedTask] = []
    skipped: list[tuple[int, str]] = []
    aborted: list[Task] = []
    errors: list[str] = []
    batch_tokens = 0

    try:
        issues = fetch_eligible(repo_cfg)
    except Exception as e:
        log.error("fetch_eligible failed: %s", e)
        errors.append(f"fetch_eligible: {e}")
        ended_at = datetime.now(timezone.utc)
        return RunReport(
            started_at=started_at,
            ended_at=ended_at,
            done=[],
            parked=[],
            skipped=[],
            aborted=[],
            errors=errors,
            summary="",
            token_usage=0,
        )

    log.info("fetched %s eligible issues from %s", len(issues), repo_cfg.slug)

    to_triage, resumed = partition_eligible(issues, store)

    if resumed or to_triage:
        log.info(
            "batch partition: %d resumed, %d to triage, %d already-handled",
            len(resumed), len(to_triage), len(issues) - len(resumed) - len(to_triage),
        )

    wallclock_exhausted = False
    for task in resumed:
        try:
            check_wallclock(started_at, cfg)
        except GuardrailViolation as ge:
            log.warning("wallclock guard fired mid-batch: %s", ge)
            errors.append(f"wallclock budget exhausted: {ge}")
            wallclock_exhausted = True
            break

        try:
            result_task = process_task(task, cfg, store, dry_run=dry_run)
        except Exception as e:
            log.error("resumed task %s raised: %s", task.id, e)
            errors.append(f"{task.id}: {type(e).__name__}: {e}")
            continue

        batch_tokens += result_task.token_usage
        if result_task.status == "done":
            done.append(result_task)
        elif result_task.status == "aborted":
            aborted.append(result_task)

    if to_triage and not wallclock_exhausted:
        try:
            triaged = triage_batch(to_triage, cfg, dry_run=dry_run)
        except Exception as e:
            log.error("triage_batch failed: %s", e)
            errors.append(f"triage_batch: {e}")
            triaged = []

        for task, tr in triaged:
            try:
                check_wallclock(started_at, cfg)
            except GuardrailViolation as ge:
                log.warning("wallclock guard fired mid-batch: %s", ge)
                errors.append(f"wallclock budget exhausted: {ge}")
                break

            try:
                status = _dispatch_triaged(task, tr, cfg, store, dry_run=dry_run)
            except Exception as e:
                log.error("task %s raised: %s", task.id, e)
                errors.append(f"{task.id}: {type(e).__name__}: {e}")
                continue

            # DOABLE tasks (done/failed/aborted) consumed tokens via process_task;
            # read the persisted total back so failed attempts still count.
            if status in ("done", "failed", "aborted"):
                processed = store.get_task(task.id)
                if processed is not None:
                    batch_tokens += processed.token_usage

            if status == "done":
                done.append(store.get_task(task.id) or task)
            elif status == "aborted":
                aborted.append(store.get_task(task.id) or task)
            elif status == "parked":
                base = task.model_dump()
                base.pop("question", None)
                parked.append(
                    ParkedTask(
                        **base,
                        question=tr.reason or "Triage classified as NEED_INPUT - clarification required.",
                        parked_at=datetime.now(timezone.utc),
                    )
                )
            elif status == "skipped":
                skipped.append((task.issue_number, tr.reason))

    ended_at = datetime.now(timezone.utc)
    return RunReport(
        started_at=started_at,
        ended_at=ended_at,
        done=done,
        parked=parked,
        skipped=skipped,
        aborted=aborted,
        errors=errors,
        summary="",
        token_usage=batch_tokens,
    )
